[build]
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/embedded.html"
  status = 200

[context.production.environment]
  FUB_API_KEY = "fka_0oHt62NxmsExO6x69p08ix82zx8ii1hzrj"
  CLOUDCMA_API_KEY = "742f4a46e1780904da090d721a9bae7b"
  ATTOM_API_KEY = "83d56a0076ca0aeefd240b3d397ce708"